[variables]
NIXPACKS_PHP_VERSION = "8.3"
PHP_VERSION = "8.3"

[phases.install]
cmds = [
  "composer install --no-dev --ignore-platform-reqs --no-scripts --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = ["npx playwright install --with-deps chromium"]
