<?php

$disabledAds = [
    'ads', 'ads_player', 'facebook_show_interstitial', 'ad_show_interstitial',
    'ad_interstitial', 'ad_banner', 'ad_face_audience_interstitial',
    'ad_face_audience_banner', 'wach_ads_to_unlock',
    'wach_ads_to_unlock_player', 'appodeal_show_interstitial',
    'ad_unit_id_native_enable', 'appodeal_banner', 'appodeal_interstitial',
    'startapp_banner', 'startapp_interstitial', 'unityads_banner',
    'unityads_interstitial', 'enable_banner_bottom', 'ad_face_audience_native',
    'appnext_banner', 'appnext_interstitial', 'vungle_banner',
    'vungle_interstitial', 'appnext_interstitial_show', 'ironsource_banner',
    'ironsource_interstitial', 'unity_show', 'applovin_native',
    'applovin_banner', 'applovin_interstitial', 'applovin_interstitial_show',
    'vungle_interstitial_show', 'ironsource_interstitial_show',
];

$settings = [
    'id' => 1,
    'latestVersion' => '1.0.0',
    'app_name' => env('EASYPLEX_APP_NAME', 'El-Nemr TV'),
    'app_packagename' => env('EASYPLEX_PACKAGE_NAME', 'com.elnemrtv.app'),
    'app_url_android' => '',
    'privacy_policy' => '',
    'tmdb_api_key' => env('TMDB_API_KEY', ''),
    'tmdb_lang' => 'en',
    'paypal_client_id' => '',
    'paypal_amount' => '0',
    'paypal_currency' => 'USD',
    'stripe_publishable_key' => '',
    'hxfile_api_key' => '',
    'default_payment' => 'Free',
    'default_network' => '',
    'default_network_player' => '',
    'default_cast_option' => 'Google Cast',
    'default_layout_networks' => 'Grid',
    'default_trailer_default' => 'Youtube',
    'default_substitle_option' => 'None',
    'default_downloads_options' => 'Internal',
    'default_youtube_quality' => 'auto',
    'default_media_placeholder_path' => '',
    'user_agent' => 'El-Nemr TV',
    'update_title' => '',
    'releaseNotes' => '',
    'url' => '',
    'custom_message' => '',
    'custom_banner_image' => '',
    'custom_banner_image_link' => '',
    'mantenance_mode_message' => '',
    'reset_password_message' => '',
    'webview_link' => '',
    'facebook_url' => '',
    'twitter_url' => '',
    'instagram_url' => '',
    'telegram_url' => '',
    'featured_home_numbers' => 10,
    'next_episode_timer' => 10,
    'streaming' => 1,
    'anime' => 1,
    'livetv' => 1,
    'networks' => 1,
    'enable_download' => 1,
    'resume_offline' => 1,
    'favoriteonline' => 1,
    'enable_upcoming' => 1,
    'enable_pinned' => 1,
    'enable_previews' => 1,
    'autosubstitles' => 0,
    'allow_adm' => 0,
    'download_premuim_only' => 0,
    'email_verify' => 0,
    'force_login' => 0,
    'force_update' => 0,
    'force_inappupdate' => 0,
    'force_password_access' => 0,
    'flag_secure' => 0,
    'vpn' => 0,
    'root_detection' => 0,
    'mantenance_mode' => 0,
    'enable_custom_message' => 0,
    'enable_custom_banner' => 0,
    'enable_webview' => 0,
    'enable_comments' => 0,
    'server_dialog_selection' => 0,
    'livetv_multi_servers' => 0,
    'notification_separated' => 0,
    'separate_download' => 0,
    'enable_vlc' => 0,
];

foreach ($disabledAds as $key) {
    $settings[$key] = 0;
}

return ['public_settings' => $settings];
